name: "Terra"
depend: [ "Gaea" ]
main: "com.dfsek.terra.Terra"
version: "1.2.0-BETA"
load: "STARTUP"
api-version: "1.16"
softdepend: [ "WorldEdit" ]
commands:
  terra:
    description: "Terra base command"
    usage: "/terra "
    aliases: [ "te" ]
    permission: "terra.command"
  locate:
    description: "Locate a Terra Structure"
    usage: "/locate <STRUCTURE_ID> <radius>"
    permission: "terra.locate"