name: Terra
depend: [ "Gaea" ]
main: com.dfsek.terra.Terra
version: 1.0.0
load: STARTUP
api-version: "1.15"
softdepend: ["WorldEdit"]
commands:
  terra:
    description: Terra base command
    usage: /terra reload
    aliases: [te]
    permission: terra.command