name: Terra
depend: [ "Gaea" ]
main: com.dfsek.terra.Terra
version: 1.0.2-BETA
load: STARTUP
api-version: "1.16"
softdepend: [ "WorldEdit" ]
commands:
  terra:
    description: Terra base command
    usage: /terra reload
    aliases: [ te ]
    permission: terra.command