debug:
  commands: false
  log: false
  profiler: false
  script: false
dump-default: true
biome-search-resolution: 4
cache:
  structure: 32
  sampler: 128
  biome-provider: 32
script:
  max-recursion: 1000