modLoader = "javafml"
loaderVersion = "[36,)"
license = "GNU General Public License, version 3.0"
issueTrackerURL = "https://github.com/PolyhedralDev/Terra/issues/"
[[mods]]
modId = "terra"
version = "@VERSION@"
displayName = "Terra"
displayURL = "https://github.com/PolyhedralDev/Terra/"
authors = "dfsek & Terra contributors"
description = "@DESCRIPTION@"
[[dependencies.terra]]
modId = "forge"
mandatory = true
versionRange = "[36,)"
ordering = "NONE"
side = "BOTH"